authentication/urls.py
from django.urls import path
from .views import login_user, signup, homepage, logout, profile
app_name = "authentication"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("login", login_user, name='login'),
    path('signup', signup, name='signup'),
    path("logout", logout, name='logout'),
    path("profile", profile, name="profile")
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('authentication.urls', namespace='authentication'))
]

authentication/models.py
from django.db import models

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", required=True, max_length=100)
    password = forms.CharField(
        label="password", required=True, widget=forms.PasswordInput())

authentication/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def homepage(request):
    return render(request, 'homepage.html')


def login_user(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            print("user ->", user)
            if user:
                login(request, user)
                return redirect("/")
    return render(request, 'login.html', {'form': form})


def signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    return render(request, 'signup.html', {'form': form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect("/login")


@login_required(login_url="/login")
def profile(request):
    return render(request, 'profile.html')

authentication/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Authentication System</title>
    </head>

    <body>
        {% if request.user.is_authenticated %}
        <h3>System is Logged In with Username: {{request.user.username}}</h3>
        <a href="{% url 'authentication:logout'%}">Logout</a>
        {%else%}
        <h3>Please Login?</h3>
        <a href="{% url 'authentication:login'%}">Login From Here</a>
        <h3>Doesnot Have Account.</h3>
        <a href="{% url 'authentication:signup'%}">SignUp From Here</a>
        {%endif%}
    </body>

</html>

authentication/templates/login.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">
</form>

authentication/templates/profile.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>my-profile</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
        <script src='main.js'></script>
    </head>

    <body>
        <h3> This is my profile page.</h3>
    </body>

</html>

authentication/templates/signup.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Signup">
</form>